### ISSUE TITLE
issues with installing and running

### ISSUE THREAD

**Issue by mrtunes** [collective-soundworks/soundworks-template#1]
looking forward to experimenting with this!

after pulling this repository on my machine, i run an npm install (also sudo npm install -g), and a bunch of errors come back. then i go into src/server and try to run the index.es6.js file. 

```
elliott:soundworks-template mrtunes$ sudo npm install
npm WARN package.json template@0.3.1 No repository field.
npm WARN deprecated gulp-es6-transpiler@1.0.1: Deprecated. Check out [gulp-babel](https://github.com/babel/gulp-babel) instead.
npm ERR! Failed resolving git HEAD (https://github.com/collective-soundworks/soundworks.git) fatal: ambiguous argument 'v0.3.0': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (https://github.com/collective-soundworks/soundworks.git) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (https://github.com/collective-soundworks/soundworks.git) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (https://github.com/collective-soundworks/soundworks.git) 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 v0.3.0
npm ERR! fatal: ambiguous argument 'v0.3.0': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mrtunes/GitHub/soundworks-template/npm-debug.log
```

trying to run a server: 

```
elliott:server mrtunes$ node index.es6.js
/Users/mrtunes/GitHub/soundworks-template/src/server/index.es6.js:17
class MyPerformance extends serverSide.Performance {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by NorbertSchnell** [comment]
The bad news is that we won't fix it :-)
The good news is that we are just about to release Soundworks 1.0 with a new template and two example applications (*Drops* and *Soundfield*) that should work (and if ever they don't work for you we will are super motivated to fix and help very quickly until it works also for you).
Watch out for the release beginning of next week...
If you're very impatient, checkout the *develop* branch (and let us know how it works for you).

**Comment by mrtunes** [comment]
Ok I'm just curious why this doesn't work? Should the repository be taken
down?

I understand that the Loop conference was quite a few months ago, and the
video of your talk just got released so more people might be headed this
way.

Looking forward to trying the next versions.
